

###

GET http://localhost:8080/attestat/11 HTTP/1.1
content-type: application/json



# 201 (Created) {"id":"1"}
# 404 (Not Found)

###

POST http://localhost:8080/attestat/create HTTP/1.1
content-type: application/json

{
  "name": "Мармеладово",
  "region": "Мармеладовая область",
  "district": "Сказочный",
  "population": 333757,
  "foundation": 2022
}

# 201 (Created) {"id":"1"}
# 404 (Not Found)
###
GET http://localhost:8080/attestat/district/Приволжский
content-type: application/json
###
GET http://localhost:8080/attestat/population/range
content-type: application/json

{
  "start": 15000,
  "end": 70000
}
###
DELETE http://localhost:8080/attestat/delete/769 HTTP/1.1
content-type: application/json

# 200 (OK)
# 404 (Not Found)

###

PUT http://localhost:8080/attestat/population/769 HTTP/1.1
content-type: application/json

{
  "population": 1500000
}

# 200 (OK)
# 404 (Not Found)

###
GET http://localhost:8080/attestat/foundation/range

{
  "start" : 900,
  "end" : 1400
}
###
